### ISSUE TITLE
Simplexmlparser

### ISSUE THREAD

**Issue by idkjs** [ocsigen/ocsimore#14]
Where can I find Simplexmlparser or its equivalent?

Thank you.

**Comment by kit-ty-kate** [comment]
This was a Tyxml module removed in tyxml.4.3.0 (https://github.com/ocsigen/tyxml/pull/197).
Ocsigenserver used this module in the past and you can see how they replaced it by `xml-light` here: https://github.com/ocsigen/ocsigenserver/pull/153
